#!/bin/bash

# Auto-Build Environment Setup
# Spec 002: Fix Git merge and configure Deepgram SDK
# Generated by Planner Agent

set -e

echo "========================================"
echo "Epic 2: Deepgram Voice Agent V1 Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if .venv exists
if [ ! -d "auto-claude/.venv" ]; then
    echo -e "${YELLOW}Creating Python virtual environment...${NC}"
    python -m venv auto-claude/.venv
fi

# Activate virtual environment
echo "Activating virtual environment..."
source auto-claude/.venv/bin/activate

# Install Python dependencies
echo "Installing Python dependencies..."
pip install -q deepgram-sdk python-dotenv 2>/dev/null || {
    echo -e "${RED}Failed to install Python dependencies${NC}"
    exit 1
}

echo -e "${GREEN}Dependencies installed successfully${NC}"

# ============================================
# GIT MERGE VERIFICATION
# ============================================

echo ""
echo "========================================"
echo "Git Repository Status"
echo "========================================"

# Check current branch
CURRENT_BRANCH=$(git branch --show-current)
echo "Current branch: $CURRENT_BRANCH"

# Check if merge is needed
if git merge-base --is-ancestor master main 2>/dev/null; then
    echo -e "${GREEN}Git merge already completed${NC}"
else
    echo -e "${YELLOW}Git merge may be required (unrelated histories)${NC}"
    echo "The coder agent will handle this during implementation"
fi

# ============================================
# ENVIRONMENT CHECK
# ============================================

echo ""
echo "========================================"
echo "Environment Check"
echo "========================================"

# Check if .env exists
if [ -f ".env" ]; then
    echo -e "${GREEN}.env file exists${NC}"

    # Check for DEEPGRAM_API_KEY
    if grep -q "DEEPGRAM_API_KEY=" .env; then
        echo -e "${GREEN}DEEPGRAM_API_KEY is set${NC}"
    else
        echo -e "${RED}DEEPGRAM_API_KEY not found in .env${NC}"
    fi

    # Check for OPENAI_API_KEY
    if grep -q "OPENAI_API_KEY=" .env; then
        echo -e "${GREEN}OPENAI_API_KEY is set${NC}"
    else
        echo -e "${YELLOW}OPENAI_API_KEY not found in .env (required for OpenAI Think provider)${NC}"
    fi
else
    echo -e "${RED}.env file not found${NC}"
fi

# ============================================
# PROJECT STRUCTURE
# ============================================

echo ""
echo "========================================"
echo "Project Structure"
echo "========================================"

# Create backend directory if not exists
if [ ! -d "backend" ]; then
    mkdir -p backend
    echo "Created backend/ directory"
fi

if [ -d "backend" ]; then
    echo -e "${GREEN}backend/ directory exists${NC}"

    # Check for Python files
    if [ -f "backend/main.py" ]; then
        echo -e "${GREEN}backend/main.py exists${NC}"
    else
        echo -e "${YELLOW}backend/main.py will be created${NC}"
    fi

    if [ -f "backend/agent.py" ]; then
        echo -e "${GREEN}backend/agent.py exists${NC}"
    else
        echo -e "${YELLOW}backend/agent.py will be created${NC}"
    fi

    if [ -f "backend/requirements.txt" ]; then
        echo -e "${GREEN}backend/requirements.txt exists${NC}"
    else
        echo -e "${YELLOW}backend/requirements.txt will be created${NC}"
    fi
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Setup Complete!"
echo "========================================"
echo ""
echo "Next Steps:"
echo "  1. Git merge (force merge with --allow-unrelated-histories)"
echo "  2. Create Python files (main.py, agent.py, requirements.txt)"
echo "  3. Install Deepgram SDK"
echo "  4. Configure agent settings"
echo "  5. Implement keepAlive() function"
echo ""
echo "Spec Directory: .auto-claude/specs/002-fix-git-merge-and-configure-deepgram-sdk/"
echo ""
echo "To continue implementation, run:"
echo ""
echo "  source auto-claude/.venv/bin/activate && python auto-claude/run.py --spec 002 --parallel 1"
echo ""
